
const regionInfo = {
    "Ilocos Region": {
        "Ilocos Norte":{
            Adams           : [],
            Bacarra         : [],
            Badoc           : [],
            Bangui          : [],                
            Batac           : [],
            Burgos          : [],
            Carasi          : [],
            Currimao        : [],
            Dingras         : [],
            Dumalneg        : [],
            Espiritu        : [],
            "Laoag City"    : [],
            Marcos          : [],
            "Nueva Era"     : [],
            Pagudpud        : [],
            Paoay           : [],
            Pasuquin        : [],
            Piddig          : [],
            Pinili          : [],
            "San Nicolas"   : [],  
            Sarrat          : [],
            Solsona         : [],
            Vintar          : [],
        }, 
        "Ilocos Sur":{
            Alilem          : ["Alilem Daya (Pob.)","Amilongan","Anaao","Apang","Apaya","Batbato","Daddaay","Dalawa","Kiat","Demog"],
            Banayoyo        : ["Bagbagotot","Banbanaal","Bisangol","Cadanglaan","Casilagan Norte","Casilagan Sur","Elefante","Guardia","Lintic","Lopez","Montero","Naguimba","Pila","Poblacion"],
            Bantay          : ["Aggay","An-annam","Balaleng","Banaoang","Bulag","Buquig","Cabalanggan","Cabaroan","Cabusligan","Capangdanan","Guimod","Lingsat","Malingeb","Mira","Naguiddayan",
                                "Ora","Paing","Puspus","Quimmarayan","Sagneb","Sagpat","San Mariano (Sallacong)","San Isidro","San Julian","Sinabaan","Taguiporo","Taleb","Tay-ac",
                                "Barangay 1 (Pob.)","Barangay 2 (Pob.)","Barangay 3 (Pob.)","Barangay 4 (Pob.)","Barangay 5 (Pob.)","Barangay 6 (Pob.)"],
            Burgos          : [],
            Cabugao         : [],
            Candon          : [],
            Caoayan         : [],
            Cervantes       : [],
            Galimuyod       : [],
            "Gregorio del Pilar" : [],  
            Lidlida         : [],
            Magsingal       : [],
            Nagbukel        : [],
            Narvacan        : [],
            Quirino         : [],
            Salcedo         : [],
            "San Emilio"    : [],
            "San Esteban"   : [],
            "San Ildefonso" : [],
            "San Juan"      : [],
            "San Vicente"   : [],
            Santa           : [],
            "Santa Catalina": [],
            "Santa Cruz"    : [],
            "Santa Lucia"   : [],
            "Santa Maria"   : [],
            "Santiago"      : [],
            "Santo Domingo" : [], 
            Sicay           : [],
            Sinait          : [],
            Sugpon          : [],
            Suyo            : [],
            Tagudin         : [],
            Vigan           : [],       
        },
        "La Union": {
            Agoo          : [],
            Aringay       : [],
            Bacnotan      : [],
            Bagulin       : [],
            Balaoan       : [],
            Bangar        : [],
            Bauang        : [],
            Burgos        : [],
            Caba          : [],
            Damortis      : [],
            Luna          : [],
            Naguilian     : [],
            Pugo          : [],
            Rosario       : [],
            "San Fernando": [], 
            "San Gabriel" : [],
            "San Juan"    : [],
            Santol        : [],
            "Sto. Tomas"  : [], 
            Sudipen       : [],
            Tubao         : [],
        },
        Pangasinan: {
            Agno:           [],
            Aguilar:        [],
            Alaminos:       [],
            Alcala:         [],
            Anda:           [],
            Asingan:        [],
            Balungao:       [],
            Bani:           [],
            Basista:        [],
            Bautista:       [],
            Bayambang:      [],
            Binalonan:      [],
            Binmaley:       [],
            Bolinao:        [],
            Bugallon:       [],
            Burgos:         [],
            Calasiao:       [],
            "Dagupan City": [],
            Dasol:          [],
            Infanta:        [],
            Labrador:       [],
            Laoac:          [],
            Lingayen:       [],
            Mabini:         [],
            Malasiqui:      [],
            Manaoag:        [],
            mangaldan:      [],
            Mangatarem:     [],
            Mapandan:       [],
            Natividad:      [],
            Pozorrubio:     [],
            Rosales:        [],
            "San Carlos City":[],   
            "San Fabian":   [],
            "San Jacinto ": [],
            "San Manuel":   [],
            "San Nicolas":  [],
            "San Quintin":  [],
            Sison:          [],
            "Sta. Barbara": [],   
            "Sta. Maria":   [],
            "Sto. Tomas":   [],
            Sual:           [],
            Tayug:          [],
            Umingan:        [],
            Urbiztondo:     [],
            Urdaneta:       [],
            Villasis:       [],
        }
    },
    "Cagayan Valley":{
        Batanes:{
            Basco	       :[],
            Itbayat	       :[],
            Ivana	       :[],
            Mahatao	       :[],
            Sabtang	       :[],
            Uyugan         :[],
        },
        Cagayan:{
            Abulug          :[],
            Alcala          :[],
            Allacapan       :[],
            Amulung         :[],
            Aparri          :[],
            Baggao	        :[],
            Ballesteros     :[],
            Buguey	        :[],
            Calayan	        :[],
            Camalaniugan    :[],
            Claveria        :[],	
            Enrile	        :[],
            Gattaran        :[],
            Gonzaga         :[],
            Iguig	        :[],
            "Lal-lo"	    :[],
            Lasam           :[],
            Pamplona        :[],
            Peñablanca	    :[],
            Piat	        :[],
            Rizal	        :[],
            "Sanchez-Mira"  :[],	
            "Santa Ana"	    :[],
            "Santa Praxedes":[],	
            "Santa Teresita":[],
            "Santo Niño"    :[],	
            "Solana"	    :[],
            "Tuao"          :[],	
            "Tuguegarao City":[],
        },
        Isabela:{
            Alicia	        :[],
            Angadanan	    :[],
            Aurora	        :[],
            "Benito Soliven":[],	
            Burgos	        :[],
            Cabagan	        :[],
            Cabatuan        :[],	
            "Cauayan City"  :[],
            Cordon	        :[],
            "Delfin Albano" :[],	
            Dinapigue	    :[],
            Divilacan       :[],	
            Echague	        :[],
            Gamu	        :[],
            "Ilagan City"   :[],
            Jones	        :[],
            Luna	        :[],
            Maconacon	    :[],
            Mallig	        :[],
            Naguilian	    :[],    
            Palanan         :[],
            Quezon	        :[],
            Quirino	        :[],
            Ramon	        :[],
            "Reina Mercedes":[],
            Roxas	        :[],
            "San Agustin"   :[],	
            "San Guillermo" :[],	
            "San Isidro"    :[],	
            "San Manuel"    :[],	
            "San Mariano"   :[],	
            "San Mateo"	    :[],
            "San Pablo"	    :[],
            "Santa Maria"   :[],
            "Santiago City" :[],
            "Santo Tomas"	:[],
            Tumauini        :[],
        },
        "Nueva Vizcaya":{
            "Alfonso Castañeda"	:[],
            Ambaguio	        :[],
            Aritao	            :[],
            Bagabag	            :[],
            Bambang	            :[],
            Bayombong           :[],
            Diadi	            :[],
            "Dupax del Norte"   :[],	
            "Dupax del Sur"	    :[],
            Kasibu	            :[],
            Kayapa	            :[],
            Quezon	            :[],
            "Santa Fe"	        :[],
            Solano	            :[],
            Villaverde          :[],
        },
        "Quirino Province":{
            Aglipay         :[],
            Cabarroguis     :[],
            Diffun	        :[],
            Maddela         :[],
            Nagtipunan	    :[],
            Saguday         :[],
        }
    },
    "Central Luzon":{
        Aurora:{
            Baler	        :[],
            Casiguran       :[],
            Dilasag         :[],	        
            Dinalungan	    :[],
            Dingalan        :[],	
            Dipaculao       :[],
            "Maria Aurora"  :[],
            "San Luis"      :[],
        }, 
        Bataan:{
            Abucay          :[],
            Bagac           :[],
            "Balanga City"  :[],
            Dinalupihan     :[],
            Hermosa         :[],
            Limay	        :[],
            Mariveles       :[],	
            Morong	        :[],
            Orani	        :[],
            Orion	        :[],
            Pilar	        :[],
            Samal           :[],
        }, 
        Bulacan:{
            Angat	        :[],
            Balagtas	    :[],
            Baliuag	        :[],
            Bocaue	        :[],
            Bulakan	        :[],
            Bustos	        :[],
            Calumpit	    :[],    
            "Doña Remedios Trinidad":[],	
            Guiguinto	    :[],
            Hagonoy	        :[],
            "Malolos City"  :[],
            Marilao	        :[],
            "Meycauayan City":[],
            Norzagaray	    :[],
            Obando	        :[],
            Pandi	        :[],
            Paombong        :[],	
            Plaridel        :[],	
            Pulilan	        :[],
            "San Ildefonso"	:[],
            "San Jose del Monte City" :[],
            "San Miguel"    :[],	
            "San Rafael"    :[],
            "Santa Maria"   :[],
        }, 
        Pampanga:{
            Angeles         :[],
            Apalit          :[],
            Arayat          :[],
            Bacolor         :[],
            Candaba         :[],
            Floridablanca   :[],
            Guagua          :[],
            Lubao           :[],
            Mabalacat       :[],
            Macabebe        :[],
            Magalang        :[],
            Masantol        :[],
            Mexico          :[],
            Minalin         :[],
            Porac           :[],
            "San Fernando"  :[],
            "San Luis"      :[],
            "San Simon"     :[],
            "Santa Ana"     :[],
            "Santa Rita"    :[],
            "Santo Tomas"   :[],
            Sasmuan         :[],
        }, 
        "Nueva Ecija":{
            Aliaga	            :[],
            Bongabon	        :[],
            "Cabanatuan City"   :[],
            Cabiao	            :[],
            Carranglan	        :[],
            Cuyapo	            :[],
            Gabaldon	        :[],
            "Gapan City" 	    :[],
            "General Mamerto Natividad"	:[],
            "General Tinio"	    :[],
            Guimba	            :[],
            Jaen	            :[],
            Laur	            :[],
            Licab	            :[],
            Llanera	            :[],
            Lupao	            :[],
            "Muñoz City"        :[],
            Nampicuan	        :[],
            "Palayan City"      :[],
            Pantabangan	        :[],
            Peñaranda	        :[],
            Quezon	            :[],
            Rizal               :[],
            "San Antonio"       :[],	
            "San Isidro"        :[],	
            "San Jose City"     :[],
            "San Leonardo"      :[],
            "Santa Rosa"        :[],
            "Santo Domingo"	    :[],
            Talavera	        :[],
            Talugtug	        :[],
            Zaragoza            :[],
        }, 
        Tarlac:{
            Anao	        :[],
            Bamban	        :[],
            Camiling        :[],	
            Capas	        :[],
            Concepcion      :[],	
            Gerona	        :[],
            "La Paz"	    :[],
            Mayantoc	    :[],
            Moncada         :[],
            Paniqui	        :[],
            Pura	        :[],
            Ramos	        :[],
            "San Clemente"	:[],
            "San Jose"	    :[],
            "San Manuel"    :[],	
            "Santa Ignacia" :[],	
            "Tarlac City"   :[],
            Victoria        :[],
        },
        Zambales:{
            Botolan	        :[],
            Cabangan        :[],
            Candelaria	    :[],
            Castillejos	    :[],
            Iba             :[],
            Masinloc        :[],
            Palauig         :[],
            "San Antonio"   :[],
            "San Felipe"    :[],
            "San Marcelino"	:[],
            "San Narciso"   :[],
            "Santa Cruz"    :[],	
            Subic           :[],
        }
    },
    "CALABARZON":{
        Batangas:{
            Agoncillo           :[],	
            Alitagtag           :[],	
            Balayan             :[],
            Balete	            :[],
            "Batangas City"     :[],
            Bauan	            :[],
            Calaca              :[],
            Calatagan           :[],	
            Cuenca              :[],
            Ibaan	            :[],
            Laurel              :[],
            Lemery	            :[],
            Lian	            :[],
            "Lipa City"         :[],
            Lobo	            :[],
            Mabini	            :[],
            Malvar	            :[],
            Mataasnakahoy	    :[],
            Nasugbu	            :[],
            "Padre Garcia"	    :[],
            Rosario	            :[],
            "San Jose"	        :[],
            "San Juan"	        :[],
            "San Luis"	        :[],
            "San Nicolas"	    :[],
            "San Pascual"       :[],	
            "Santa Teresita"    :[],    
            "Santo Tomas City"  :[],
            Taal	            :[],
            Talisay             :[],
            "Tanauan City"      :[], 
            Taysan	            :[],
            Tingloy	            :[],
            Tuy                 :[],
        }, 
        Cavite:{
            Alfonso                     :[],
            Amadeo	                    :[],
            "Bacoor City"               :[],
            Carmona                     :[],
            "Cavite City"               :[],
            "Dasmariñas City"           :[], 
            "General Emilio Aguinaldo"  :[],
            "General Mariano Alvarez"   :[],
            "General Trias City"        :[],
            "Imus City"                 :[],
            Indang	                    :[],
            Kawit	                    :[],
            Magallanes	                :[],
            Maragondon	                :[],
            Mendez	                    :[],
            Naic	                    :[],
            Noveleta	                :[],
            Rosario	                    :[],
            Silang	                    :[],
            "Tagaytay City"             :[],
            Tanza	                    :[],
            Ternate	                    :[],
            "Trece Martires"            :[],
        }, 
        Laguna:{
            Alaminos            :[],	
            Bay	                :[],
            "Biñan City"        :[],
            "Cabuyao City"      :[],
            "Calamba City"      :[],
            Calauan             :[],
            Cavinti	            :[],
            Famy                :[],	
            Kalayaan            :[],	
            Liliw	            :[],
            "Los Baños"	        :[],
            Luisiana	        :[],
            Lumban	            :[],
            Mabitac	            :[],
            Magdalena           :[],
            Majayjay	        :[],
            Nagcarlan	        :[],
            Paete	            :[],
            Pagsanjan	        :[],
            Pakil	            :[],
            Pangil              :[],
            Pila	            :[],
            Rizal               :[],	
            "San Pablo City"    :[],
            "San Pedro City"    :[],
            "Santa Cruz"	    :[],
            "Santa Maria"       :[],
            "Santa Rosa City"   :[],
            Siniloan	        :[],
            Victoria            :[],
        }, 
        Quezon:{
            Agdangan        :[],
            Alabat          :[],
            Atimonan        :[],
            Buenavista      :[],
            Burdeos         :[],
            Calauag         :[],
            Candelaria      :[],      
            Catanauan       :[],
            Dolores         :[],
            "General Luna"  :[],
            "General Nakar" :[],
            Guinayangan     :[],
            Gumaca          :[],
            Infanta         :[],
            Jomalig         :[],
            Lopez           :[],
            Lucban          :[],
            "Lucena City"   :[],
            Macalelon       :[],
            Mauban          :[],
            Mulanay         :[],
            "Padre Burgos"  :[],
            Pagbilao        :[],
            Panukulan       :[],
            Patnanungan     :[],
            Perez           :[],
            Pitogo          :[],
            Plaridel        :[],
            Polillo         :[],
            Quezon          :[], 
            Real            :[],
            Sampaloc        :[],
            "San Andres"    :[],
            "San Antonio"   :[],
            "San Francisco" :[],
            "San Narciso"   :[],
            Sariaya         :[],
            Tagkawayan      :[],
            Tayabas         :[],
            Tiaong          :[],
            Unisan          :[],
        }, 
        Rizal:{
            Angono          :[],
            "Antipolo City" :[],
            Baras           :[],
            Binangonan      :[],
            Cainta          :[],
            Cardona         :[],   
            Jalajala        :[],
            Morong          :[],
            Pililla         :[],
            Rodriguez       :[],
            "San Mateo"     :[],
            Tanay           :[],
            Taytay          :[],
            Teresa          :[],
        }
    },   
    "MIMAROPA Region":{
        "Mindoro Occidental":{
            "Abra de Ilog"  :[],
            Calintaan       :[],
            Looc            :[],
            Lubang          :[],
            Magsaysay       :[],
            Mamburao        :[],
            Paluan          :[],
            Rizal           :[],
            Sablayan        :[],
            "San Jose"      :[],
            "Santa Cruz"    :[],
        }, 
        "Mindoro Oriental":{
            Baco            :[],
            Bansud          :[],
            Bongabong       :[],
            Bulalacao       :[],
            Calapan         :[],
            Gloria          :[],
            Mansalay        :[],
            Naujan          :[],
            Pinamalayan     :[],
            Pola            :[],
            "Puerto Galera" :[],
            Roxas           :[],
            "San Teodoro"   :[],
            Socorro         :[],
            Victoria        :[],
        }, 
        Marinduque:{
            Boac            :[],
            Buenavista      :[],
            Gasan           :[],
            Mogpog          :[],
            "Santa Cruz"    :[],
            Torrijos        :[],
        }, 
        Romblon:{
            Alcantara       :[],
            Banton          :[],
            Cajidiocan      :[],
            Calatrava       :[],
            Concepcion      :[],
            Corcuera        :[],
            Ferrol          :[],
            Looc            :[],
            Magdiwang       :[],
            Odiongan        :[],
            Romblon         :[],
            "San Agustin"   :[],
            "San Andres"    :[],
            "San Fernando"  :[],
            "San Jose"      :[],
            "Santa Fe"      :[],
            "Santa Maria"   :[],
        },
        Palawan:{
            Aborlan         :[],
            Agutaya         :[],
            Araceli         :[],
            Balabac         :[],
            Bataraza        :[],
            "Brooke's Point":[],
            Busuanga        :[],
            Cagayancillo    :[],
            Coron           :[],
            Culion          :[],
            Cuyo            :[],
            Dumaran         :[],
            "El Nido"       :[],
            Kalayaan        :[],
            Linapacan       :[],
            Magsaysay       :[],
            Narra           :[],
            "Puerto Princesa":[],
            Quezon          :[],
            Rizal           :[],
            Roxas           :[],
            "San Vicente"   :[],
            "Sofronio Española":[],
            Taytay          :[],
        }   
    },
    "Bicol Region":{
        Albay:{
            Bacacay         :[],
            Camalig         :[],
            Daraga          :[],
            Guinobatan      :[],
            Jovellar        :[],
            "Legazpi City"  :[],
            Libon           :[],
            Ligao           :[],
            Malilipot       :[],
            Malinao         :[],
            Manito          :[],
            Oas             :[],
            "Pio Duran"     :[],
            Polangui        :[],
            "Rapu-Rapu"     :[],
            "Santo Domingo" :[],
            "Tabaco City"   :[],
            Tiwi            :[],
        },
        "Camarines Norte":{
            Basud               :[],
            Capalonga           :[],
            Daet                :[],
            "Jose Panganiban"   :[],
            Labo                :[],
            Mercedes            :[],
            Paracale            :[],
            "San Lorenzo Ruiz"  :[],
            "San Vicente"       :[],
            "Santa Elena"       :[],
            Talisay             :[],
            Vinzons             :[],
        },
        "Camarines Sur":{
            Baao            :[],
            Balatan         :[],
            Bato            :[],
            Bombon          :[],
            Buhi            :[],
            Bula            :[],
            Cabusao         :[],
            Calabanga       :[],
            Camaligan       :[],
            Canaman         :[], 
            Caramoan        :[],
            "Del Gallego"   :[],
            Gainza          :[],
            Garchitorena    :[],
            Goa             :[],
            "Iriga City"    :[],
            Lagonoy         :[],
            Libmanan        :[],
            Lupi            :[],
            Magarao         :[],
            Milaor          :[],
            Minalabac       :[],      
            Nabua           :[],
            "Naga City"     :[],
            Ocampo          :[],
            Pamplona        :[],
            Pasacao         :[],
            Pili            :[],
            Presentacion    :[],
            Ragay           :[],
            Sagñay          :[],
            "San Fernando"  :[],
            "San Jose"      :[],
            Sipocot         :[],
            Siruma          :[],
            Tigaon          :[],
            Tinambac        :[],
        },
        Catanduanes:{
            Bagamanoc       :[],
            Baras           :[],
            Bato            :[],
            Caramoran       :[],
            Gigmoto         :[],
            Pandan          :[],
            Panganiban      :[],
            "San Andres"    :[],
            "San Miguel"    :[],
            Viga            :[],
            Virac           :[],
        },
        Masbate:{
            Aroroy          :[],
            Baleno          :[],
            Balud           :[],
            Batuan          :[],
            Cataingan       :[],
            Cawayan         :[],
            Claveria        :[],
            Dimasalang      :[],
            Esperanza       :[],
            Mandaon         :[],
            "Masbate City"  :[],
            Milagros        :[],
            Mobo            :[],
            Monreal         :[],
            Palanas         :[],
            "Pio V. Corpuz" :[],
            Placer          :[],
            "San Fernando"  :[],
            "San Jacinto"   :[],
            "San Pascual"   :[],
            Uson            :[],
        },
        Sorsogon:{
            Barcelona           :[],
            Bulan               :[],
            Bulusan             :[],
            Casiguran           :[],
            Castilla            :[],
            Donsol              :[],
            Gubat               :[],
            Irosin              :[],
            Juban               :[],
            Magallanes          :[],
            Matnog              :[],
            Pilar               :[],
            "Prieto Diaz"       :[],
            "Santa Magdalena"   :[],
            "Sorsogon City"     :[],
        }
    },
    "Western Visayas":{
        Aklan:{
            Altavas         :[],
            Balete          :[],
            Banga           :[],
            Batan           :[],
            Buruanga        :[],
            Ibajay          :[],
            Kalibo          :[],
            Lezo            :[],
            Libacao         :[],
            Madalag         :[],
            Makato          :[],
            Malay           :[],
            Malinao         :[],
            Nabas           :[],
            "New Washington":[],
            Numancia        :[],
            Tangalan        :[],
        }, 
        Antique:{
            "Anini-y"       :[],
            Barbaza         :[],
            Belison         :[],
            Bugasong        :[],
            Caluya          :[],
            Culasi          :[],
            Hamtic          :[],
            "Laua-an"       :[],
            Libertad        :[],
            Pandan          :[],
            Patnongon       :[],
            "San Jose de Buenavista":[],
            "San Remigio"   :[],
            Sebaste         :[],
            Sibalom         :[],
            Tibiao          :[],
            "Tobias Fornier":[],
            Valderrama      :[],
        }, 
        Capiz:{
            Cuartero        :[],  
            Dao             :[],
            Dumalag         :[],
            Dumarao         :[],
            Ivisan          :[],
            Jamindan        :[],
            Maayon          :[],
            Mambusao        :[],
            Panay           :[],
            Panitan         :[],
            Pilar           :[],
            Pontevedra      :[],
            "President Roxas":[],
            "Roxas City"    :[],
            Sapian          :[],
            Sigma           :[],
            Tapaz           :[],

        }, 
        Guimaras:{
            Buenavista      :[],
            Jordan          :[],
            "Nueva Valencia":[],
            "San Lorenzo"   :[],
            Sibunag         :[],
        }, 
        Iloilo:{
            Ajuy            :[],
            Alimodian       :[],
            Anilao          :[],
            Badiangan       :[],
            Balasan         :[],
            Banate          :[],
            "Barotac Nuevo" :[],
            "Barotac Viejo" :[],
            Batad           :[],
            Bingawan        :[],
            Cabatuan        :[],
            Calinog         :[],
            Carles          :[],
            Concepcion      :[],
            Dingle          :[],
            Dueñas          :[],
            Dumangas        :[],
            Estancia        :[],
            Guimbal         :[],
            Igbaras         :[],
            "Iloilo City"   :[],
            Janiuay         :[],
            Lambunao        :[],
            Leganes         :[],
            Lemery          :[],
            Leon            :[],
            Maasin          :[],
            Miagao          :[],
            Mina            :[],
            "New Lucena"    :[],
            Oton            :[],
            Passi           :[],
            Pavia           :[],
            Pototan         :[],
            "San Dionisio"  :[],
            "San Enrique"   :[],
            "San Joaquin"   :[],
            "San Miguel"    :[],
            "San Rafael"    :[],
            "Santa Barbara" :[],
            Sara            :[],
            Tigbauan        :[],
            Tubungan        :[],
            Zarraga         :[],
        },
        "Negros Occidental":{
            Bacolod                 :[],
            Bago                    :[],
            Binalbagan              :[],
            Cadiz                   :[],
            Calatrava               :[],
            Candoni                 :[],
            Cauayan                 :[],
            "Enrique B. Magalona"   :[],
            Escalante               :[],
            Himamaylan              :[],
            Hinigaran               :[],
            "Hinoba-an"             :[],
            Ilog                    :[],
            Isabela                 :[],
            Kabankalan              :[],
            "La Carlota"            :[],
            "La Castellana"         :[],
            Manapla                 :[],
            "Moises Padilla"        :[],
            Murcia                  :[],
            Pontevedra              :[],
            Pulupandan              :[],
            Sagay                   :[],
            "Salvador Benedicto"    :[],
            "San Carlos"            :[],
            "San Enrique"           :[],
            Silay                   :[],
            Sipalay                 :[],
            Talisay                 :[],
            Toboso                  :[],
            Valladolid              :[],
            Victorias               :[],
        }
    },
    "Central Visayas":{
        Bohol:{
            Alburquerque        :[],
            Alicia              :[],
            Anda                :[],
            Antequera           :[],
            Baclayon            :[],
            Balilihan           :[],
            Batuan              :[],
            "Bien Unido"        :[],
            Bilar               :[],
            Buenavista          :[],
            Calape              :[],
            Candijay            :[],
            Carmen              :[],
            Catigbian           :[],
            Clarin              :[],
            Corella             :[],
            Cortes              :[],
            Dagohoy             :[],
            Danao               :[],
            Dauis               :[],
            Dimiao              :[],
            Duero               :[],
           "Garcia Hernandez"   :[],
            Getafe              :[],
            Guindulman          :[],
            Inabanga            :[],
            Jagna               :[],
            Lila                :[],
            Loay                :[],
            Loboc               :[],
            Loon                :[],
            Mabini              :[],
            Maribojoc           :[],
            Panglao             :[],
            Pilar               :[],
            "President Carlos P. Garcia"  :[],
            Sagbayan            :[],
            "San Isidro"        :[],
            "San Miguel"        :[],
            Sevilla             :[],
            "Sierra Bullones"   :[],
            Sikatuna            :[],
            Tagbilaran          :[],
            Talibon             :[],
            Trinidad            :[],
            Tubigon             :[],
            Ubay                :[],
            Valencia            :[],
        }, 
        Cebu:{
            Alcantara       :[],
            Alcoy           :[],
            Alegria         :[],
            Aloguinsan      :[],
            Argao           :[],
            Asturias        :[],
            Badian          :[],
            Balamban        :[],
            Bantayan        :[],
            Barili          :[],
            Bogo            :[],
            Boljoon         :[],
            Borbon          :[],
            Carcar          :[],
            Carmen          :[],
            Catmon          :[],
            "Cebu City"     :[],
            Compostela      :[],
            Consolacion     :[],
            Cordova         :[],
            Daanbantayan    :[],
            Dalaguete       :[],
            Danao           :[],
            Dumanjug        :[],
            Ginatilan       :[],
            "Lapu-Lapu City":[],
            Liloan          :[],
            Madridejos      :[],
            Malabuyoc       :[],
            "Mandaue City"  :[],
            Medellin        :[],
            Minglanilla     :[],
            Moalboal        :[],
            Naga            :[],
            Oslob           :[],
            Pilar           :[],
            Pinamungajan    :[],
            Poro            :[],
            Ronda           :[],
            Samboan         :[],
            "San Fernando"  :[],
            "San Francisco" :[],
            "San Remigio"   :[],
            "Santa Fe"      :[],
            Santander       :[],
            Sibonga         :[],
            Sogod           :[],
            Tabogon         :[],
            Tabuelan        :[],
            Talisay         :[],
            Toledo          :[],
            Tuburan         :[],
            Tudela          :[],
        }, 
        "Negros Oriental":{
            Amlan           :[],
            Ayungon         :[],
            Bacong          :[],
            Bais            :[],
            Basay           :[],
            Bayawan         :[],
            Bindoy          :[],    
            Canlaon         :[],
            Dauin           :[],
            Dumaguete       :[],
            Guihulngan      :[],
            Jimalalud       :[],
            "La Libertad"   :[],
            Mabinay         :[],
            Manjuyod        :[],
            Pamplona        :[],
            "San Jose"      :[],
            "Santa Catalina":[],
            Siaton          :[],
            Sibulan         :[],
            Tanjay          :[],
            Tayasan         :[],
            Valencia        :[],
            Vallehermoso    :[],
            Zamboanguita    :[],
        }, 
        Siquijor:{
            "Enrique Villanueva":[],
            Larena              :[],
            Lazi                :[],
            Maria               :[],
            "San Juan"          :[],
            Siquijor            :[],
        }
    },
    "Eastern Visayas":{
        Biliran:{
            Almeria     :[],
            Biliran     :[],
            Cabucgayan  :[],
            Caibiran    :[],
            Culaba      :[],
            Kawayan     :[],
            Maripipi    :[],
            Naval       :[],

        }, 
        "Eastern Samar":{
            Arteche             :[],
            Balangiga           :[],
            Balangkayan         :[],
            Borongan            :[],
            "Can-avid"          :[],
            Dolores             :[],
            "General MacArthur" :[],
            Giporlos            :[],
            Guiuan              :[],
            Hernani             :[],
            Jipapad             :[],
            Lawaan              :[],
            Llorente            :[],
            Maslog              :[],
            Maydolong           :[],
            Mercedes            :[],
            Oras                :[],
            Quinapondan         :[],
            Salcedo             :[],
            "San Julian"        :[],
            "San Policarpo"     :[],
            Sulat               :[],
            Taft                :[],
        }, 
        Leyte:{
            Abuyog          :[],
            Alangalang      :[],
            Albuera         :[],
            Babatngon       :[],
            Barugo          :[],
            Bato            :[],
            Baybay          :[],
            Burauen         :[],
            Calubian        :[],
            Capoocan        :[],
            Carigara        :[],
            Dagami          :[],
            Dulag           :[],
            Hilongos        :[],
            Hindang         :[],
            Inopacan        :[],
            Isabel          :[],
            Jaro            :[],
            Javier          :[],        
            Julita          :[],
            Kananga         :[],
            "La Paz"        :[],
            Leyte           :[],
            MacArthur       :[],
            Mahaplag        :[],
            "Matag-ob"      :[],
            Matalom         :[],
            Mayorga         :[],
            Merida          :[],
            "Ormoc City"    :[],
            Palo            :[],
            Palompon        :[],
            Pastrana        :[],
            "San Isidro"    :[],
            "San Miguel"    :[],
            "Santa Fe"      :[],
            Tabango         :[],
            Tabontabon      :[],
            "Tacloban City" :[],
            Tanauan         :[],
            Tolosa          :[],
            Tunga           :[],
            Villaba         :[],
        },
        "Northern Samar":{
            Allen           :[],
            Biri            :[],
            Bobon           :[],
            Capul           :[],
            Catarman        :[],
            Catubig         :[],
            Gamay           :[],
            Laoang          :[],
            Lapinig         :[],
            "Las Navas"     :[],
            Lavezares       :[],
            "Lope de Vega"  :[],
            Mapanas         :[],
            Mondragon       :[],
            Palapag         :[],
            Pambujan        :[],
            Rosario         :[],
            "San Antonio"   :[],
            "San Isidro"    :[],
            "San Jose"      :[],
            "San Roque"     :[],
            "San Vicente"   :[],
            "Silvino Lobos" :[],
            Victoria        :[],
        }, 
        Samar:{
            Almagro         :[],
            Basey           :[],    
            Calbayog        :[],
            Calbiga         :[],
            Catbalogan      :[],
            Daram           :[],
            Gandara         :[],
            Hinabangan      :[],
            Jiabong         :[],
            Marabut         :[],
            Matuguinao      :[],
            Motiong         :[],
            Pagsanghan      :[],
            Paranas         :[],
            Pinabacdao      :[],
            "San Jorge"     :[],
            "San Jose de Buan":[],
            "San Sebastian" :[],
            "Santa Margarita":[],
            "Santa Rita"    :[],
            "Santo Niño"    :[],
            "Tagapul-an"    :[],
            Talalora        :[],
            Tarangnan       :[],
            Villareal       :[],
            Zumarraga       :[],

        }, 
        "Southern Leyte":{
            Anahawan        :[],
            Bontoc          :[],
            Hinunangan      :[],
            Hinundayan      :[],
            Libagon         :[],
            Liloan          :[],
            Limasawa        :[],
            Maasin          :[],
            Macrohon        :[],
            Malitbog        :[],
            "Padre Burgos"  :[],
            Pintuyan        :[],
            "Saint Bernard" :[],
            "San Francisco" :[],
            "San Juan"      :[],
            "San Ricardo"   :[],
            Silago          :[],
            Sogod           :[],
            "Tomas Oppus"   :[],
        }
    },
    "Zamboanga Peninsula":{
        "Zamboanga del Norte":{

        },
        "Zamboanga del Sur":{

        }, 
        "Zamboanga Sibugay":{

        }, 
    },
    "Northern Mindanao":{
        Bukidnon:{

        }, 
        Camiguin:{

        }, 
        "Lanao del Norte":{

        }, 
        "Misamis Occidental":{

        },
        "Misamis Oriental":{

        }
    },
    "Davao Region":{
        "Davao de Oro (Compostela Valley)":{

        }, 
        "Davao del Norte":{

        }, 
        "Davao del Sur":{

        }, 
        "Davao Occidental":{

        }, 
        "Davao Oriental":{

        }
    },
    "SOCCSKSARGEN":{
        Cotabato:{
            Alamada         :[],
            Aleosan         :[],
            Antipas         :[],
            Arakan          :[],
            Banisilan       :[],
            Carmen          :[],
            Kabacan         :[],
            Kidapawan       :[],
            Libungan        :[],
            "M'lang"        :[],
            Magpet          :[],
            Makilala        :[],
            Matalam         :[],
            Midsayap        :[],
            Pigcawayan      :[],
            Pikit           :[],
            "President Roxas":[],
            Tulunan         :[],
        }, 
        Sarangani:{
            Alabel      :[],
            Glan        :[],
            Kiamba      :[],
            Maasim      :[],
            Maitum      :[],
            Malapatan   :[],
            Malungon    :[],
        }, 
        "South Cotabato":{
            Banga               :[],
            "General Santos City":[],
            Koronadal           :[],
            "Lake Sebu"         :[],
            Norala              :[],
            Polomolok           :[],
            "Santo Niño"        :[],
            Surallah            :[],
            "T'Boli"            :[],
            Tampakan            :[],
            Tantangan           :[],
            Tupi                :[],           
        }, 
        "Sultan Kudarat":{
            Bagumbayan          :[],
            Columbio            :[],
            Esperanza           :[],
            Isulan              :[],
            Kalamansig          :[],
            Lambayong           :[],
            Lebak               :[],
            Lutayan             :[],
            Palimbang           :[],
            "President Quirino" :[],
            "Senator Ninoy Aquino":[],
            Tacurong            :[],
        }
    },
    "CARAGA":{
        "Agusan del Norte":{
            Buenavista          :[],
            Butuan              :[],
            Cabadbaran          :[],
            Carmen              :[],
            Jabonga             :[],
            Kitcharao           :[],
            "Las Nieves"        :[],
            Magallanes          :[],
            Nasipit             :[],
            "Remedios T. Romualdez":[],
            Santiago            :[],
            Tubay               :[],
        }, 
        "Agusan del Sur":{
            Bayugan         :[],
            Bunawan         :[],
            Esperanza       :[],    
            "La Paz"        :[],
            Loreto          :[],
            Prosperidad     :[],
            Rosario         :[],
            "San Francisco" :[],
            "San Luis"      :[],
            "Santa Josefa"  :[],
            Sibagat         :[],
            Talacogon       :[],
            Trento          :[],
            Veruela         :[],
        }, 
        "Dinagat Islands":{
            Basilisa        :[],
            Cagdianao       :[],
            Dinagat         :[],
            Libjo           :[],
            Loreto          :[],
            "San Jose"      :[],
            Tubajon         :[],
        }, 
        "Surigao del Norte":{
            Alegria         :[],
            Bacuag          :[],
            Burgos          :[],
            Claver          :[],
            Dapa            :[],
            "Del Carmen"    :[],
            "General Luna"  :[],
            Gigaquit        :[],
            Mainit          :[],
            Malimono        :[],
            Pilar           :[],
            Placer          :[],
            "San Benito"    :[],
            "San Francisco" :[],
            "San Isidro"    :[],
            "Santa Monica"  :[],
            Sison           :[],
            Socorro         :[],
            "Surigao City"  :[],
            "Tagana-an"     :[],
            Tubod           :[],
        },  
        "Surigao del Sur":{
            Barobo          :[],
            Bayabas         :[],
            Bislig          :[],
            Cagwait         :[],
            Cantilan        :[],
            Carmen          :[],
            Carrascal       :[],
            Cortes          :[],
            Hinatuan        :[],
            Lanuza          :[],
            Lianga          :[],
            Lingig          :[],
            Madrid          :[],
            Marihatag       :[],
            "San Agustin"   :[],
            "San Miguel"    :[],
            Tagbina         :[],
            Tago            :[],
            Tandag          :[],
        }
    },
    "NCR":{
        "Metro Manila": {
            "Caloocan City"     :[], 
            "Las Piñas"         :[],
            Makati              :[], 
            Malabon             :[],
            Mandaluyong         :[],
            Manila              :[],
            Marikina            :[],
            Muntinlupa          :[],
            Navotas             :[],
            Parañaque           :[],
            "Pasay City"        :[],
            "Pasig  City"       :["Bagong Ilog", "Bagong Katipunan", "Bambang", "Buting"],
            Pateros             :["Aguho", "Magtangol","Martires Del 96","Poblacion"],
            "Quezon City"       :[],
            "San Juan"          :[],
            Taguig              :[],
            Valenzuela          :[],
        }            
    },
    CAR:{
        Abra:{
            Bangued         :[],
            Boliney         :[],
            Bucay           :[],
            Bucloc          :[],
            Daguioman       :[],
            Danglas         :[],
            Dolores         :[],
            "La Paz"        :[],
            Lacub           :[],
            Lagangilang     :[],
            Lagayan         :[],
            Langiden        :[],
            "Licuan-Baay"   :[],
            Luba            :[],
            Malibcong       :[],
            Manabo          :[],
            Peñarrubia      :[],
            Pidigan         :[],
            Pilar           :[],
            Sallapadan      :[],
            "San Isidro"    :[],
            "San Juan"      :[],
            "San Quintin"   :[],
            Tayum           :[],
            Tineg           :[],
            Tubo            :[],
            Villaviciosa    :[],
        }, 
        Apayao:{
            Calanasan       :[],
            Conner          :[],
            Flora           :[],
            Kabugao         :[],
            Luna            :[],
            Pudtol          :[],
            "Santa Marcela" :[],

        }, 
        "Benguet":{
            Atok            :[],
            "Baguio City"   :[],
            Bakun           :[],
            Bokod           :[],
            Buguias         :[],
            Itogon          :[],
            Kabayan         :[],
            Kapangan        :[],
            Kibungan        :[],
            "La Trinidad"   :[],
            Mankayan        :[],
            Sablan          :[],
            Tuba            :[],
            Tublay          :[],
        }, 
        Ifugao:{
            Aguinaldo       :[],
            "Alfonso Lista" :[],
            Asipulo         :[],
            Banaue          :[],
            Hingyon         :[],
            Hungduan        :[],
            Kiangan         :[],
            Lagawe          :[],
            Lamut           :[],
            Mayoyao         :[],
            Tinoc           :[],
        },  
        Kalinga:{
            Balbalan    :[],
            Lubuagan    :[],
            Pasil       :[],
            Pinukpuk    :[],
            Rizal       :[],
            Tabuk       :[],
            Tanudan     :[],
            Tinglayan   :[],
        },
        "Mountain Province":{
            Barlig      :[],
            Bauko       :[],
            Besao       :[],
            Bontoc      :[],
            Natonin     :[],
            Paracelis   :[],
            Sabangan    :[],
            Sadanga     :[],
            Sagada      :[],
            Tadian      :[],
        }
    },  
    "BARMM":{
        Basilan:{
            Akbar               :[],
            "Al-Barka"          :[],
            "Hadji Mohammad Ajul":[],
            "Hadji Muhtamad"    :[],
            "Isabela City"      :[],
            Lamitan             :[],
            Lantawan            :[],
            Maluso              :[],
            Sumisip             :[],
            "Tabuan-Lasa"       :[],
            "Tipo-Tipo"         :[],
            Tuburan             :[],
            "Ungkaya Pukan"     :[],
        }, 
        "Lanao del Sur":{
            "Amai Manabilang"   :[],
            "Bacolod-Kalawi"    :[],
            Balabagan           :[],
            Balindong           :[],
            Bayang              :[],
            Binidayan           :[],
           "Buadiposo-Buntong"  :[],
            Bubong              :[],
            Butig               :[],
            Calanogas           :[],
            "Ditsaan-Ramain"    :[],
            Ganassi             :[],
            Kapai               :[],
            Kapatagan           :[],
            "Lumba-Bayabao"     :[],
            "Lumbaca-Unayan"    :[],
            Lumbatan            :[],
            Lumbayanague        :[],
            Madalum             :[],
            Madamba             :[],
            Maguing             :[],    
            Malabang            :[],    
            Marantao            :[],
            Marawi              :[],
            Marogong            :[],
            Masiu               :[],
            Mulondo             :[],
            Pagayawan           :[],       
            Piagapo             :[],
            Picong              :[],
            "Poona Bayabao"     :[],
            Pualas              :[],
            Saguiaran           :[],
            "Sultan Dumalondong":[],
            "Tagoloan II"       :[],
            Tamparan            :[],
            Taraka              :[],
            Tubaran             :[],
            Tugaya              :[],
            Wao                 :[],
        }, 
        Maguindanao:{
            Ampatuan                    :[],
            Barira                      :[],
            Buldon                      :[],
            Buluan                      :[],
            "Cotabato City"             :[],
            "Datu Abdullah Sangki"      :[],
            "Datu Anggal Midtimbang"    :[],
            "Datu Blah T. Sinsuat"      :[],
            "Datu Hoffer Ampatuan"      :[],
            "Datu Montawal"             :[],
            "Datu Odin Sinsuat"         :[],
            "Datu Paglas"               :[],
            "Datu Piang"                :[],
            "Datu Salibo"               :[],
            "Datu Saudi-Ampatuan"       :[],
            "Datu Unsay"                :[],
            "General Salipada K. Pendatun":[],
            Guindulungan                :[],
            Kabuntalan                  :[],
            Mamasapano                  :[],
            Mangudadatu                 :[],
            Matanog                     :[],
            "Northern Kabuntalan"       :[],
            Pagalungan                  :[],
            Paglat                      :[],
            Pandag                      :[],
            Parang                      :[],
            "Rajah Buayan"              :[],
            "Shariff Aguak"             :[],
            "Shariff Saydona Mustapha"  :[],
            "South Upi"                 :[],
            "Sultan Kudarat"            :[],
            "Sultan Mastura"            :[],
            "Sultan sa Barongis"        :[],
            "Sultan Sumagka"            :[],
            Talayan                     :[],
            Upi                         :[],
        }, 
        Sulu:{
            Banguingui              :[],
            "Hadji Panglima Tahil"  :[],
            Indanan                 :[],    
            Jolo                    :[],
            "Kalingalan Caluang"    :[],
            Lugus                   :[],
            Luuk                    :[],
            Maimbung                :[],
            "Old Panamao"           :[],
            Omar                    :[],
            Pandami                 :[],
            "Panglima Estino"       :[],
            Pangutaran              :[],
            Parang                  :[],
            Pata                    :[],
            Patikul                 :[],
            Siasi                   :[],
            Talipao                 :[],
            Tapul                   :[],
        }, 
        "Tawi-Tawi":{
            Bongao              :[],
            Languyan            :[],
            Mapun               :[],
            "Panglima Sugala"   :[],
            "Sapa-Sapa"         :[],
            Sibutu              :[],
            Simunul             :[],
            Sitangkai           :[],
            "South Ubian"       :[],
            Tandubas            :[],
            "Turtle Islands"    :[],
        }
    }
  };


  window.onload = function () {
  
    const regionSelection = document.querySelector("#region"),
      provinceSelection = document.querySelector("#province"),
      citySelection = document.querySelector("#city"),
      brgySelection = document.querySelector("#brgy");


      for (let region in regionInfo) {
        regionSelection.options[regionSelection.options.length] = new Option(
          region,
          region
        );
      }

        //Todo: Region Changed

    regionSelection.onchange = (e) => {
        provinceSelection.disabled = false;
    
        provinceSelection.length = 1; 
        citySelection.length = 1; 
        brgySelection.length = 1; 
    
        // if (e.target.selectedIndex < 1) return; // done
    
        // todo: Load province by looping over regionInfo
        for (let province in regionInfo[e.target.value]) {
          provinceSelection.options[provinceSelection.options.length] = new Option(
            province,
            province
          );
        }
    }
  
        //todo: Province Changed
  provinceSelection.onchange = (e) => {
    citySelection.disabled = false;

    citySelection.length = 1; 
    brgySelection.length = 1; 

    for (let city in regionInfo[regionSelection.value][e.target.value]) {
      citySelection.options[citySelection.options.length] = new Option(
        city,
        city
       );
    }
  };

    //todo: City Changed
   citySelection.onchange = (e) => {
        brgySelection.disabled = false;
        brgySelection.length = 1; 

        let brgy =  regionInfo[regionSelection.value][provinceSelection.value][e.target.value];

        for (let i=0; i < brgy.length; i++) {
          brgySelection.options[brgySelection.options.length] = new Option(
            brgy[i],
            brgy[i]
          );
        }
      };
      
    }



